### ISSUE TITLE
爬评论也寄律师函？？？？

### ISSUE THREAD

**Issue by tanxiaolong** [dongweiming/commentbox#1]
rt

**Comment by dongweiming** [comment]
要不然我为啥删掉

**Comment by tanxiaolong** [comment]
问题评论是网友的评论啊  谁说评论的所有权归网易云音乐了，服务条款只是提到“网友的评论也属于网易云音乐的‘# 内容’”

> 11、信息储存及相关知识产权

网易公司对网易云音乐软件上所有服务将尽力维护其安全性及方便性，但对服务中出现的信息（包括但不限于用户发布的信息、用户自主创立的歌单）删除或储存失败不承担任何责任。另外网易公司有权判定用户的行为是否符合本服务条款的要求，如果用户违背了本服务条款的规定，网易公司有权中止或者终止对提供其网易云音乐服务。

网易公司尊重知识产权并注重保护用户享有的各项权利。在网易云音乐软件所含服务中，用户可能需要通过发表评论等各种方式向网易公司提供内容。在此情况下，用户仍然享有此等内容的完整知识产权。用户在提供内容时将授予网易公司一项全球性的免费许可，允许网易公司使用、传播、复制、修改、再许可、翻译、创建衍生作品、出版、表演及展示此等内容。
